import type { CSSProperties } from 'react'

/*
  Olipy-inspired design contract.
  Deep-blue ink on soft neutral canvas, tight-serif display + geist body.
*/

export const editableRootStyle = {
  '--slot4-page-bg': '#f4f5f7',
  '--slot4-page-text': '#022997',
  '--slot4-panel-bg': '#ffffff',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#022997b3',
  '--slot4-soft-muted-text': '#02299780',
  '--slot4-accent': '#022997',
  '--slot4-accent-fill': '#022997',
  '--slot4-accent-soft': '#d0ddff',
  '--slot4-accent-secondary': '#0038d6',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#022997',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e8ebf0',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#eef0f4',
  '--slot4-lavender': '#d0ddff',
  '--slot4-gray': '#e8ebf0',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f4f5f7',
  '--editable-page-text': '#022997',
  '--editable-container': '1392px',
  '--editable-border': '#02299726',
  '--editable-border-strong': '#02299766',
  '--editable-nav-bg': '#f4f5f7',
  '--editable-nav-text': '#022997',
  '--editable-nav-active': '#022997',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#022997',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#022997',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  borderStrong: 'border-[var(--editable-border-strong)]',
  darkBorder: 'border-white/15',
  shadow: 'shadow-[0_1px_2px_rgba(2,41,151,0.05)]',
  shadowStrong: 'shadow-[0_18px_40px_-18px_rgba(2,41,151,0.35)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(2,41,151,0.05),rgba(2,41,151,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[87rem] px-5 sm:px-8 lg:px-12',
    sectionNarrow: 'mx-auto w-full max-w-[70rem] px-5 sm:px-8 lg:px-12',
    sectionRead: 'mx-auto w-full max-w-[50rem] px-5 sm:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-28',
    sectionYLg: 'py-20 sm:py-28 lg:py-36',
    sectionYSm: 'py-12 sm:py-16',
  },
  layout: {
    safeGrid: 'grid gap-8 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.2fr_0.8fr] lg:items-start',
    rail: 'flex snap-x gap-6 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'text-[11px] font-medium uppercase tracking-[0.24em] text-[var(--slot4-accent)] editable-sans',
    heroTitle: 'editable-serif text-[3rem] font-normal leading-[1.05] tracking-[-0.02em] sm:text-[4.4rem] lg:text-[5.6rem]',
    displayTitle: 'editable-serif text-[3.6rem] font-normal leading-[1.02] tracking-[-0.03em] sm:text-[5rem] lg:text-[7rem]',
    sectionTitle: 'editable-serif text-[2.6rem] font-normal leading-[1.1] tracking-[-0.02em] sm:text-[3.25rem] lg:text-[3.75rem]',
    subsectionTitle: 'editable-serif text-[1.5rem] font-normal leading-[1.2] tracking-[-0.01em] sm:text-[1.9rem]',
    cardTitle: 'editable-serif text-[1.3rem] font-normal leading-[1.15] tracking-[-0.01em] sm:text-[1.5rem]',
    body: 'text-[1rem] leading-[1.7] editable-sans sm:text-[1.1rem]',
    lead: 'text-[1.15rem] leading-[1.55] editable-sans sm:text-[1.3rem]',
    emphasis: 'editable-serif italic',
    label: 'text-[0.75rem] uppercase tracking-[0.22em] editable-mono',
  },
  badge: {
    pill: 'inline-flex items-center gap-2 rounded-full border border-[var(--editable-border-strong)] px-3 py-1 text-[11px] font-medium uppercase tracking-[0.2em] text-[var(--slot4-accent)] editable-sans',
    accentPill: 'inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent-soft)] px-3 py-1 text-[11px] font-medium uppercase tracking-[0.2em] text-[var(--slot4-accent)] editable-sans',
    softPill: 'inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 text-[11px] font-medium uppercase tracking-[0.2em] text-[var(--slot4-accent)] editable-sans',
  },
  surface: {
    card: `rounded-[1rem] border ${editablePalette.border} ${editablePalette.surfaceBg}`,
    soft: `rounded-[1rem] border ${editablePalette.border} ${editablePalette.warmBg}`,
    dark: `rounded-[1rem] ${editablePalette.darkBg} ${editablePalette.darkText}`,
    accent: `rounded-[1rem] bg-[var(--slot4-accent-soft)] text-[var(--slot4-accent)]`,
  },
  button: {
    primary: 'editable-btn-slide inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-[13px] font-medium uppercase tracking-[0.16em] text-[var(--slot4-on-accent)] transition duration-500 hover:bg-[var(--slot4-accent-secondary)] active:scale-[0.98]',
    secondary: 'editable-btn-slide inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border-strong)] bg-transparent px-7 py-3.5 text-[13px] font-medium uppercase tracking-[0.16em] text-[var(--slot4-accent)] transition duration-500 hover:border-[var(--slot4-accent)] hover:bg-[var(--slot4-accent)] hover:text-[var(--slot4-on-accent)] active:scale-[0.98]',
    accent: 'editable-btn-slide inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-soft)] px-7 py-3.5 text-[13px] font-medium uppercase tracking-[0.16em] text-[var(--slot4-accent)] transition duration-500 hover:bg-[var(--slot4-accent)] hover:text-[var(--slot4-on-accent)] active:scale-[0.98]',
    ghost: 'inline-flex items-center gap-1.5 text-[13px] font-medium uppercase tracking-[0.2em] text-[var(--slot4-accent)] transition hover:opacity-70',
  },
  media: {
    frame: `relative overflow-hidden rounded-[1rem] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden ${editablePalette.mediaBg}`,
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-700 hover:-translate-y-1',
    fade: 'transition duration-500 hover:opacity-80',
    zoom: 'transition duration-[900ms] group-hover:scale-[1.04]',
  },
} as const

export const aiLayoutRules = [
  'All color/type comes from editableRootStyle CSS vars; do not hardcode hex inside JSX.',
  'Display headings use serif via editable-serif class; labels use mono via editable-mono.',
  'Sections consume dc.shell.sectionY rhythm; extra-large hero uses sectionYLg.',
  'Wrap section headers/grids in EditableReveal with staggered index props.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
